### ISSUE TITLE
New peers in a crdt cluster don't receive state

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/ipfs-cluster#784] opened 2019-05-20 03:31 UTC
**Additional information:**
 - OS: Ubuntu
 - IPFS Cluster version: 0.10.1+git9692e368f3e1a4f5eec224dd165822550e28c7a0
 - Installation method: built from source

**Describe the bug:**

New clusters initialized from this version don't receive the current state from other peers. `ipfs-cluster-ctl status` on new members returns nothing. Pinning a CID then running `ipfs-cluster-ctl status` does return the correct result, but that new CID doesn't appear on other peers' status.

Other peers are shown in `ipfs-cluster-ctl peers ls`.

**Comment by hsanjuan** [comment] 2019-05-20 08:22
You would need to wait a little bit until someone pins something or re-broadcast is retriggered (every minute by default, controlled by `rebroadcast_interval`).

**Comment by NatoBoram** [comment] 2019-05-20 10:02
After a full night and some manual pins added, I can confirm that the state is not transferred to the new peers.

`ipfs-cluster-ctl peers ls` :
```
Sees 2 other peers
```

`ipfs-cluster-ctl pins ls` and `ipfs-cluster-ctl status` :
```
 
```

**Comment by NatoBoram** [comment] 2019-05-20 17:58
I added the node responsible for pinning in everyone's `trusted_peers`, and now the state was received. However, `ipfs-cluster-ctl status` will only display yourself and peers that trust you. Looks good to me.

I think it would be appropriate to consider the bootstrap target a `trusted_peers` regardless of config. It would also make sense to have your own `trusted_peers` be propagated to those who trust you.

**Comment by hsanjuan** [comment] 2019-05-20 18:16
> I added the node responsible for pinning in everyone's trusted_peers, and now the state was received.

Ah indeed! That was pretty obvious. At this point you are testing things that I haven't had time to setup myself.

> ipfs-cluster-ctl status will only display yourself and peers that trust you

Yes, if a peer does not trust you it won't let you sniff around or touch anything.

> I think it would be appropriate to consider the bootstrap target a trusted_peers regardless of config. It would also make sense to have your own trusted_peers be propagated to those who trust you.

The plan is to make configuration template, so that any peer can start with something like `ipfs-cluster-service --config /ipfs/Qm...` and that template will have the `trusted_peers` and the `bootstrap` correctly configured.

Auto-configuring the bootstrap peer(s) as "trusted" is probably the intended behaviour for 95% of cases, but technically you should be able to bootstrap to anyone (trusted or not).

**Comment by NatoBoram** [comment] 2019-05-21 03:46
I could reproduce this issue on another computer. I have 3 peers bootstrapped to another one, and *one* of those 3 isn't receiving the state. They *all* have the exact same configurations and versions of IPFS and IPFS-Cluster.

Here's all the info about the defective peer.

### System

```yaml
OS: elementary OS 5.0 Juno x86_64 
Host: S551LN 1.0 
Kernel: 4.15.0-51-generic 
Uptime: 54 mins 
Packages: 1897 
Shell: bash 4.4.19 
Terminal: /dev/pts/0 
CPU: Intel i7-4500U (4) @ 3.000GHz 
GPU: NVIDIA GeForce 840M 
GPU: Intel Haswell-ULT 
Memory: 1037MiB / 7860MiB 
```

### IPFS

```yaml
go-ipfs version: 0.4.21-rc1-cf3b6c43d
Repo version: 7
System version: amd64/linux
Golang version: go1.12.5
```

### IPFS-Cluster

```
0.10.1+git30ba6f82dd8050e4df302f162ac29b3a4f4f8715
```

<details>
<summary>Peers</summary>

```markdown
12D3KooWCWXtr2t7uLRdzwX9CitfLi5WApSbC4jY812NXdcRkWj4 | hp-server | Sees 3 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/ipfs/12D3KooWCWXtr2t7uLRdzwX9CitfLi5WApSbC4jY812NXdcRkWj4
    - /ip4/135.23.195.89/tcp/35218/ipfs/12D3KooWCWXtr2t7uLRdzwX9CitfLi5WApSbC4jY812NXdcRkWj4
    - /ip4/192.168.1.139/tcp/9096/ipfs/12D3KooWCWXtr2t7uLRdzwX9CitfLi5WApSbC4jY812NXdcRkWj4
  > IPFS: QmP1aP6pa4N82Yy2NUFzRW7AWSF8St3x3H1b6vd2fg5SPR
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmP1aP6pa4N82Yy2NUFzRW7AWSF8St3x3H1b6vd2fg5SPR
    - /ip4/135.23.195.89/tcp/62370/ipfs/QmP1aP6pa4N82Yy2NUFzRW7AWSF8St3x3H1b6vd2fg5SPR
    - /ip4/192.168.1.139/tcp/4001/ipfs/QmP1aP6pa4N82Yy2NUFzRW7AWSF8St3x3H1b6vd2fg5SPR
    - /ip6/::1/tcp/4001/ipfs/QmP1aP6pa4N82Yy2NUFzRW7AWSF8St3x3H1b6vd2fg5SPR

12D3KooWEr3PcBU3aqCqzDEHADg1CmSZ2CeYyuFCVaCi2DXdhEVX | nato-elementary | Sees 3 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/ipfs/12D3KooWEr3PcBU3aqCqzDEHADg1CmSZ2CeYyuFCVaCi2DXdhEVX
    - /ip4/135.23.195.89/tcp/55101/ipfs/12D3KooWEr3PcBU3aqCqzDEHADg1CmSZ2CeYyuFCVaCi2DXdhEVX
    - /ip4/192.168.1.102/tcp/9096/ipfs/12D3KooWEr3PcBU3aqCqzDEHADg1CmSZ2CeYyuFCVaCi2DXdhEVX
    - /ip4/192.168.1.142/tcp/9096/ipfs/12D3KooWEr3PcBU3aqCqzDEHADg1CmSZ2CeYyuFCVaCi2DXdhEVX
  > IPFS: QmcEN7ka3MfvkVhwZu1RGSoPstx72vC5YoZ9Yg4VBXYEq7
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmcEN7ka3MfvkVhwZu1RGSoPstx72vC5YoZ9Yg4VBXYEq7
    - /ip4/135.23.195.89/tcp/63691/ipfs/QmcEN7ka3MfvkVhwZu1RGSoPstx72vC5YoZ9Yg4VBXYEq7
    - /ip4/192.168.1.102/tcp/4001/ipfs/QmcEN7ka3MfvkVhwZu1RGSoPstx72vC5YoZ9Yg4VBXYEq7
    - /ip4/192.168.1.142/tcp/4001/ipfs/QmcEN7ka3MfvkVhwZu1RGSoPstx72vC5YoZ9Yg4VBXYEq7
    - /ip6/::1/tcp/4001/ipfs/QmcEN7ka3MfvkVhwZu1RGSoPstx72vC5YoZ9Yg4VBXYEq7

12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY | lineageos-on-ipfs | Sees 3 other peers
  > Addresses:
    - /ip4/10.20.0.5/tcp/9096/ipfs/12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY
    - /ip4/127.0.0.1/tcp/9096/ipfs/12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY
    - /ip4/159.89.116.13/tcp/9096/ipfs/12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY
  > IPFS: QmSqLAXiJiteNbuNPY4Y5Lp4iKiUmqhCkBZSedZEutktVs
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmSqLAXiJiteNbuNPY4Y5Lp4iKiUmqhCkBZSedZEutktVs
    - /ip4/159.89.116.13/tcp/4001/ipfs/QmSqLAXiJiteNbuNPY4Y5Lp4iKiUmqhCkBZSedZEutktVs
    - /ip6/2604:a880:cad:d0::17:2001/tcp/4001/ipfs/QmSqLAXiJiteNbuNPY4Y5Lp4iKiUmqhCkBZSedZEutktVs
    - /ip6/::1/tcp/4001/ipfs/QmSqLAXiJiteNbuNPY4Y5Lp4iKiUmqhCkBZSedZEutktVs

12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74 | nato-hu | Sees 3 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/9096/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
    - /ip4/135.23.195.89/tcp/50030/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
    - /ip4/192.168.1.122/tcp/9096/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
    - /ip4/192.168.122.1/tcp/9096/ipfs/12D3KooWEcEmcMy2MMHHCqH2w4Hx3TPrpHSKpSWLXKiW5uVKpC74
  > IPFS: QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/127.0.0.1/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/135.23.195.89/tcp/65074/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/192.168.1.122/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip4/192.168.122.1/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
    - /ip6/::1/tcp/4001/ipfs/QmUJKWDGYwNsihCrGCxQYEbM2MME28LsMhgCdtfRJ7S8t9
```

</details>

It doesn't appear in `lineageos-on-ipfs`'s status.

```markdown
QmWA4Lqv1AQjEbuurrXnCybag1M1jeQbTXUcBkBFoUoG1B :
    > lineageos-on-ipfs : REMOTE: Post http://127.0.0.1:5001/api/v0/pin/ls?arg=QmWA4Lqv1AQjEbuurrXnCybag1M1jeQbTXUcBkBFoUoG1B&type=recursive: dial tcp 127.0.0.1:5001: connect: connection refused | 2019-05-20T22:40:30.190533394-04:00
    > hp-server       : PIN_ERROR: Post http://127.0.0.1:5001/api/v0/pin/ls?arg=QmWA4Lqv1AQjEbuurrXnCybag1M1jeQbTXUcBkBFoUoG1B&type=recursive: dial tcp 127.0.0.1:5001: connect: connection refused | 2019-05-21T03:41:39.245751714Z
    > nato-hu         : REMOTE | 2019-05-21T03:39:14.336839625Z
    > nato-elementary : UNPINNED | 2019-05-21T03:45:07.334229478Z
```

**Comment by NatoBoram** [comment] 2019-05-21 05:35
Can probably be tested by having peers join the collaborative pinset.

> **`cluster.secret` :** `c89099b9149e2482df0b62f5f77c5db5e04d09dc919d33a60e628e10ed331b2e`
> 
> **`consensus.crdt.trusted_peers` :** `12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY`
> 
> **Bootstrap :** `ipfs-cluster-service daemon --upgrade --bootstrap /ip4/159.89.116.13/tcp/9096/ipfs/12D3KooWAG38EVPM1Mrw1YBDe1wuFKS23LiZXq8FGjdypmh6RbgY --consensus crdt`

**Comment by hsanjuan** [comment] 2019-05-21 07:38
is `cosnensus.crdt.cluster_name` set to "ipfs-cluster"? While I can connect, it seems the connection drops rather quickly and I don't think I'm getting the root head of the DAG that would allow me to fetch the state.

**Comment by NatoBoram** [comment] 2019-05-23 04:28
Ooh. Well, that resolved the issue. So `cosnensus.crdt.cluster_name` kind of acts like a read permission?

**Comment by hsanjuan** [comment] 2019-05-23 11:47
@NatoBoram it's the pubsub topic that peers subscribe to for updates, in case you have several clusters running on the same libp2p swarm (i.e. you could run cluster now on the public ipfs network if you really wanted, but using the global DHT likely makes things slower).

**Comment by hsanjuan** [comment] 2019-05-23 22:06
I'll close this as it seems there's no issue after all, but I'll re-open if anything similar comes up during my testing.

**Closed by hsanjuan** 2019-05-23 22:06 UTC
Labels: bug, invalid

**Comment by NatoBoram** [comment] 2019-05-24 01:52
> i.e. you could run cluster now on the public ipfs network if you really wanted, but using the global DHT likely makes things slower

Sounds fun, I want to test that! How do I do it? What does it do differently?

**Comment by hsanjuan** [comment] 2019-05-24 08:35
> How do I do it?

Runing cluster peers (in crdt mode) with an empty `secret` should allow them to join the global DHT. With the stuff in #792 you should be able to put IPFS bootstrappers (from `./ipfs/config`) in the cluster `peerstore` file. And then your peers should bootstrap to those and might be able to find each others. I haven't tried any of this.

> What does it do differently?

Doesn't do anything differently, just removes the encryption layer that isolated the swarm from other swarms  (like the IPFS one).
