### ISSUE TITLE
Pre existing pin added to new peer causes strange behavior.

### ISSUE THREAD

**Issue by obo20** [ipfs/ipfs-cluster#888] opened 2019-08-15 16:32 UTC
**Additional information:**
 - OS: MacOS and Ubuntu 18
 - IPFS Cluster version: v0.11.0-rc6
 - Installation method: dist.ipfs.io

**Describe the bug:**

I was doing some testing with the CRDT version of cluster on one node and added a new node into the mix. Since cluster doesn't automatically pull in the pre-existing pin-list on new peers, I tested adding a few of the pins on the original node via: "ipfs-cluster-ctl pin add CID"

The replication settings on both peers are:
* ipfs_cluster_replication_factor_min: 1
* ipfs_cluster_replication_factor_max: 2

When I did this, and then ran ipfs-cluster-ctl status CID I received the following:
CID :
    > MacOS-Original-Node: REMOTE |  2019-08-15T16:13:00.745072Z
    > New-Node : PINNED | 2019-08-15T16:13:01.305904959Z

What I expected to see was the following:
CID :
    > MacOS-Original-Node: PINNED |  2019-08-15T16:13:00.745072Z
    > New-Node : PINNED | 2019-08-15T16:13:01.305904959Z

I'm not sure if this is intended behavior or not, but it seems like a bug to me.

**Comment by hsanjuan** [comment] 2019-08-15 16:41
> Since cluster doesn't automatically pull in the pre-existing pin-list on new peers

It does, it just takes about 20 seconds or so. If you add `"rebroadcast_interval": "5s"` to the "crdt" section you can further reduce this.

Hi, this is not intended behaviour a priori, but there might be some reasons. It would look like you added the pin shortly after starting the New-Node ? And are you sure you added the content in the Original Node and not in the new node? In the latter case, it could be that the new node had not received any metrics from the Original Node yet, and therefore did not put it on the list.

`ipfs-cluster-ctl health metrics freespace` should show metrics from both peers (in both peers). Does the problem persist after a while or does it start assigning to both?

**Comment by obo20** [comment] 2019-08-15 17:23
What I mean is if we have CID-A and it’s pinned on Node-1
Then if I add Node-2 to the cluster
Node-2 won’t automatically pin CID-A (this is expected)
However, if I run ipfs-cluster-ctl pin add CID-A on Node-2
it should pin to both nodes should it not?
since the replication-factor max is set to 2

I further tested by passing in the "--replication 2" flag on the same CID and after that, I received the following, which is expected: 
CID : 
    > MacOS-Original-Node : PINNED | 2019-08-15T16:36:44.452299Z
    > New-Node : PINNED | 2019-08-15T16:36:44.301923629Z

It seems like when the second node joins the cluster and "repins" the content, it still uses the old replication amount even though the new node has replication_max of 2

**Comment by hsanjuan** [comment] 2019-08-15 18:04
it should pin to both nodes should it not?

Ah, no. The pin already exists in the global database and is allocated to the minimum amouint and you added exactly with the same options so it fully skips doing it. When you set the replication factor to two, you modified the pin, thus it did Pin the item with the new allocations.

I understand this might not be what a user expects so happy to change it:

*When a pin is submitted and it already exists, attempt to fill up allocations up to replication-factor max.*

Context: https://github.com/ipfs/ipfs-cluster/blob/master/cluster.go#L1334

The current behavior is that when calling Allocate on a pin, we don't change allocations when the current number is between "needed" (minimum) and "wanted" (maximum). We only change it when the current number is below the minimum, in which case we attempt to obtain the maximum.

**Comment by obo20** [comment] 2019-08-15 20:11
That's good to know. 

I will say from a UX standpoint I found that pretty unexpected, as the CID basically swapped nodes, but the replication number stayed the same.

However I'm not quite sure if this will be problematic for us yet. This was basically something that I discovered in what I would consider a "not production" scenario, but I'll have to do some digging to determine whether or not this is problematic for other things.

**Comment by hsanjuan** [comment] 2019-08-22 11:11
> CID basically swapped nodes, 

wait, was it pinned in one and then pinned in the other but unpinned (or "remote") in the first one?

**Comment by obo20** [comment] 2019-09-02 20:39
@hsanjuan yes that's what happened

**Comment by hsanjuan** [comment] 2019-09-06 16:51
@obo20 I think this was a bug and it's fixed by #912

**Closed** 2019-09-09 08:25 UTC
Labels: needs feedback from submitter
