### ISSUE TITLE
ipfs-cluster pin add error

### ISSUE THREAD

**Issue by zicmama** [ipfs/ipfs-cluster#756] opened 2019-04-16 22:29 UTC
#### Pre-check

* [x] This is not a IPFS Cluster website content issue ([file those here](https://github.com/ipfs/ipfs-cluster-website/issues))
* [x] I read the [troubleshooting section](https://cluster.ipfs.io/documentation/troubleshooting/) of the website and it did not help
* [x] I searched for similar issues in the repo without luck
* [x] All my peers are running the same cluster version
* [x] All my peers are configured using the same cluster `secret`

#### Basic information

* [x] Version information (mark as appropiate):
  * [ ] Master
  * [ ] Release candidate for next version
  * [x] Latest stable version
  * [ ] An older version I should not be using
* [x] Type (mark as appropiate):
  * [x] Bug
  * [ ] Feature request
  * [ ] Enhancement
* [x] Operating system (mark as appropiate):
  * [x] Linux
  * [ ] macOS
  * [ ] Windows
  * [ ] Other: `which?`
* [x] Installation method (mark as appropiate):
  * [x] Binaries from dist.ipfs.io
  * [ ] Built from sources
  * [ ] Docker
  * [ ] Snap
  * [ ] Other: `which?`

#### Description

I have just build a private network / ipfs-cluster with 3 nodes.

After adding 224GB of data, I receive an error when I want to distribute pinning.

    ipfs-cluster-ctl pin add Qmam8wSeLVqGAjpKfVrRtrhHMjbBrd3jDCPRkJjfrq7iwf
    Qmam8wSeLVqGAjpKfVrRtrhHMjbBrd3jDCPRkJjfrq7iwf :

        : CLUSTER_ERROR: Time.UnmarshalBinary: unsupported version | 2019-04-16T22:37:51.979418655+02:00
        rock64 : PINNED | 2019-04-16T22:37:50.905047818+02:00
        : CLUSTER_ERROR: Time.UnmarshalBinary: unsupported version | 2019-04-16T22:37:51.979861392+02:00

ipfs-cluster-ctl peers ls show the 2 other nodes connected.
3 new pins only were transmitted to other nodes ( ipfs-cluster-ctl pin ls )

    arm node
    /usr/local/bin/ipfs daemon --enable-gc --mount --routing=dhtclient
    "StorageMax": "5GB"
    QmaJMgTygtDkswBEhnJ449ktrRTZa9RcsZHRX3QDccmTSj

    amd64 node
    /usr/local/bin/ipfs-cluster-service daemon
    "StorageMax": "700GB"
    Qmb6Gyy3KFWTxWh4v6fBeh5ANxAF6YAahWQtokmsNsqGda

    arm64 node
    /usr/local/bin/ipfs-cluster-service daemon --enable-gc --mount
    "StorageMax": "1.5TB"
    QmYZJoSmkPZZZmLKpq26hSo1i49tT752Z4ERx6SSXhbSjP

Discuss:
https://discuss.ipfs.io/t/ipfs-cluster-pin-add-error/5233

**Comment by hsanjuan** [comment] 2019-04-17 08:34
Hi, are all your nodes running the same version of ipfs-cluster-service and ipfs-cluster-ctl?

**Comment by zicmama** [comment] 2019-04-17 10:37
Yes, I downloaded them from https://dist.ipfs.io/#go-ipfs
Different init for each.
amd64: ipfs init -p server
arm: ipfs init -p lowenergy
arm64: ipfs init

**Comment by hsanjuan** [comment] 2019-04-17 11:38
I'm talking about ipfs-cluster-service and ipfs-cluster-ctl

**Comment by zicmama** [comment] 2019-04-17 15:00
Oh! Of course, I download all from the same page

**Comment by hsanjuan** [comment] 2019-04-17 15:20
Can you post `ipfs-cluster-service --version` and `ipfs-cluster-ctl --version` for all peers?

**Comment by zicmama** [comment] 2019-04-17 19:18
ipfs-cluster-service version 0.10.1
ipfs-cluster-ctl version 0.10.1
On all platform same answer

**Comment by zicmama** [comment] 2019-04-17 19:21
I am wondering what is the ipfs-cluster-service communication layer (pubsub?)

**Comment by ItalyPaleAle** [comment] 2019-04-17 21:55
I am having the same issue with ipfs-cluster-ctl 0.10.1 on ARM64 architecture. The ARM node joins a cluster (other nodes are X86), but when I run `ipfs-cluster-ctl status` I see a bunch of similar errors:

````sh
[multihash of pin] :
    > [multihash of node] : CLUSTER_ERROR: msgpack decode error [pos 166]: invalid length of bytes for decoding time - expecting 4 or 8 or 12, got 15 | 2019-04-17T21:52:06.603110192Z
    > [multihash of node] : CLUSTER_ERROR: msgpack decode error [pos 164]: invalid length of bytes for decoding time - expecting 4 or 8 or 12, got 15 | 2019-04-17T21:52:06.602406543Z
    > [Name of current node]         : PINNED | 2019-04-17T21:50:35.427414439Z
    > [multihash of node] : CLUSTER_ERROR: msgpack decode error [pos 171]: invalid length of bytes for decoding time - expecting 4 or 8 or 12, got 15 | 2019-04-17T21:52:06.602623899Z
````

This happens on ipfs-cluster-ctl 0.10.1. It was working fine on 0.10.

Possibly an endianness error?

**Comment by hsanjuan** [comment] 2019-04-18 08:52
Hmm... my findings...

So it seems that I may have screwed the 0.10.1 build and it was built without go modules. That means dependencies used may be of a newer version that what's go-modded (probably a very recent version).

A commit in ugorji/go introduced changed how `time` is encoded: https://github.com/ugorji/go/commit/debb8e2d2e8bd8cf1e9b6d806cf5e58df86b970c and is known to produce these errors when decoding something encoded in the old fashion. However, this change was a while ago and I would assume it was in 0.10.0. If all nodes are running 0.10.1 they should be running the same version of this library in any case.

Then it is highlighted here that this happens when arm64 decodes time as encoded in x86 and vice-versa so this might be a bug in ugorji/go.

There might be a workaround using `TimeNotBuiltIn` (https://github.com/ugorji/go/commit/037e5aa7efe80d77d79a345684aa9e167540cbad).

For the moment I have opened an issue https://github.com/ugorji/go/issues/294 and will follow-up.

**Comment by ItalyPaleAle** [comment] 2019-04-18 16:11
I can confirm my setup (mixed cluster of x86 and arm64) was working fine with 0.10.0.

**Comment by hsanjuan** [comment] 2019-04-18 16:14
@ItalyPaleAle I thought we did not have arm64 builds for 0.10.0 (?) Did you build manually? And if so, would you be able to try by manually building 0.10.1 (on both arm64 and x86)..

**Comment by ItalyPaleAle** [comment] 2019-04-18 17:55
@hsanjuan Yes, I built it manually on arm64.

I just tried re-building ipfs-cluster on arm64 from source. The steps are a bit different from 0.10.0 because of the addition of go modules

1. Clone the repo (outside of the GOPATH, or it will fail as it won't use go modules by default)
2. Run `go get`
3. Run `make`

After this, the new binaries are working for me. I can run commands like `ipfs-cluster-ctl status` and it's successful (it sees all pins and all nodes).

I did the above **only on arm64**. It doesn't look like it was necessary to re-compile on x64 (also, on x64 I'm running ipfs-cluster via Docker, so using manual builds there is hard for me).

**Comment by ItalyPaleAle** [comment] 2019-04-18 17:57
Oh, one thing I should point out... I just noticed on your travis configuration file that you're using Go 1.11 for the builds. In my machine (where I re-compiled this) I am using Go 1.12

**Comment by hsanjuan** [comment] 2019-04-25 14:12
So it would seem it's about different architectures having been built with different versions of dependencies (although I can't quite explain that). I'm going to try to rebuild the 0.10.1 release properly this week and this should fix itself. Luckily the data involved here is not anything persisted.

**Comment by hsanjuan** [comment] 2019-04-26 14:53
Hello, I have rebuilt the 0.10.1 release in dist.ipfs.io and it should now have been built with go modules etc. Closing this as preliminarly fixed, but please try it out and re-open if things still don't work.

**Closed by hsanjuan** 2019-04-26 14:53 UTC
Labels: bug, in progress, priority:high
